### ISSUE TITLE
Do not understand what the output means

### ISSUE THREAD

**Issue by MichaelScofield** [RichardWarburton/honest-profiler#101]
Forgive me if this question is too simple, but I cannot really understand what the output means from the command line (runs on linux and not have a GUI):

Flat Profile:
2.03 sun.reflect.DelegatingMethodAccessorImpl.invoke

Does this mean the "sun.reflect.DelegatingMethodAccessorImpl.invoke" method took 203% cpu time?

And

Tree Profile:
 1.00 java.lang.Thread.run
  0.00 java.util.concurrent.ThreadPoolExecutor$Worker.run

Tree profile makes me even more confused.

**Comment by nitsanw** [comment]
Hi,
Can you please send the HPL log for analysis?
From your output it would also seem you are not using latest version. Can you verify with latest?
Thanks,
Nitsan

**Comment by RichardWarburton** [comment]
Excellent Question @nitsanw - I was going to reply this today to ask the same question!

**Comment by MichaelScofield** [comment]
@nitsanw @RichardWarburton 

I'm using the version downloaded from http://insightfullogic.com/honest-profiler.zip, and the unzipped files are marked from January 8, 2015.

The output file is too large to paste all of it here, so I keep the main structures and omit some of the contents and paste it as following:

> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.el7_1.x86_64/bin/
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.el7_1.x86_64/bin//../lib/tools.jar
Printing Profile for: /tmp/logs/log.hpl
11:33:59.859 [main] DEBUG c.i.honest_profiler.core.Conductor - Reached end of log for FileLogSource{file=/tmp/logs/log.hpl} due to NOTHING
Number of stack traces: 154869

> Flat Profile:
        0.12 java.net.SocketInputStream.socketRead0
        0.11 java.net.SocketOutputStream.socketWrite0
        0.04 sun.misc.Unsafe.park
        0.08 java.util.concurrent.locks.LockSupport.parkNanos
        0.03 sun.reflect.Reflection.getCallerClass
        0.03 sun.misc.Unsafe.unpark
        0.02 java.lang.Object.wait
        0.02 sun.nio.ch.EPollArrayWrapper.epollWait
        0.02 sun.nio.ch.EPollArrayWrapper.interrupt
        0.01 sun.nio.ch.FileDispatcherImpl.write0
        0.01 java.net.PlainSocketImpl.socketAvailable
        0.01 java.lang.String.intern

> skipped ...

> Tree Profile:
 1.00 java.lang.Thread.run
  0.00 java.util.concurrent.ThreadPoolExecutor$Worker.run
   0.00 java.util.concurrent.ThreadPoolExecutor.runWorker

> skipped ...

**Comment by RichardWarburton** [comment]
By the way - I've uploaded a new version of the binary at  http://insightfullogic.com/honest-profiler.zip which you might want to test.

**Comment by MichaelScofield** [comment]
hi @RichardWarburton
looks like the newer version requires "GLIBCXX_3.4.21" while I'm running on a CentOS 7.0 and not able to find it.

```
$ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

will try to compile GLIBCXX_3.4.21 on my CentOS 7. but it takes quite a lot effort. wish me luck.

**Comment by RichardWarburton** [comment]
Eurgh, someone else reported that problem as well. Let me investigate further.

**Comment by MichaelScofield** [comment]
@RichardWarburton thx, that would be awesome (and quite a burden release for me) to support lower version of GLIBCXX because upgrading it is a very tough quest after I did some google :)

**Comment by RichardWarburton** [comment]
So, after investigation I've concluded the simplest way for me to do this is to run a chroot or VM with an older GLIBCXX and compile the build on there. I'll try to get this setup soon.

**Comment by RichardWarburton** [comment]
@MichaelScofield I've uploaded a binary to http://insightfullogic.com/honest-profiler.zip which should work on as old as GLIBCXX_3.4.11.

I'll try and keep the build baselined to this version of GCC for as long as possible.

I'm also going to close this issue as I think its about an out of date UI being used. If the current UI is also confusing then please re-open.

**Comment by MichaelScofield** [comment]
OK, thanks @RichardWarburton :)
