### ISSUE TITLE
Not able to start the JVM after configuring the agent in wrapper.conf

### ISSUE THREAD

**Issue by sattishv** [RichardWarburton/honest-profiler#105]
Hi Richard,

First i would like to thank your for developing a profiler which overcomes the safepoint barrier. We have used all kinds of profilers starting from open source to commercial(Appdynamics,Dynatrace,Yourkit.JProfiler,JMC etc. This one caught our attention a lot.
Appreciate your tremendous effort.
Tried to configure honest profiler agent for one of our Java app. But while trying to start the service got JVM exited with the below listed error.

STATUS | wrapper  | 2016/02/11 17:59:28 | Launching a JVM...
ERROR  | wrapper  | 2016/02/11 17:59:28 | JVM exited while loading the application.
INFO   | jvm 1    | 2016/02/11 17:59:28 | Error occurred during initialization of VM
INFO   | jvm 1    | 2016/02/11 17:59:28 | Could not find agent library /x/opt/honest-profiler/liblagent.so in absolute path, with error: libjawt.so: cannot open shared object file: No such file or directory

Config settings used:
wrapper.java.additional.38=-agentpath:/x/opt/honest-profiler/liblagent.so=interval=7,logPath=/x/opt/honest-profiler/log.hpl

Because we use wrapper conf to set JVM options
Kernel version  we use: 2.6.18-348.4.1.el5  x86_64 

agent folder had all the required permissions. Checked the user permissions to reflect the same the applications uses.

Could you please review and let me know how we can overcome as we are very much interested in honest profiler.

Thanks
Sattish.

**Comment by RichardWarburton** [comment]
Hi @sattishv,

Thanks for your issue but upon further investigation it looks like the missing libjawt is a system configuration issue rather than a bug in honest-profiler as such.

There are a couple of links online explaining how you can fix this issue, see for example http://forums.spiralknights.com/en/node/51696 and https://bbs.archlinux.org/viewtopic.php?id=124432.

I'm going to close this issue for now, but if those links don't get you to a solution then feel free to re-open the issue with more information.

regards,

  Richard

**Comment by sattishv** [comment]
Hi Richard,

Thanks for your response.But still i couldn't load the agent library(liblagent.so). I explicitly set the LD_LIBRARY_PATH to load the agent lib but still the same error. Would like to know whether the version of glibc plays a role here because my ldd command shows few lib links are missing.

[root@stage2lp31 honest-profiler]# ldd liblagent.so
./liblagent.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./liblagent.so)
./liblagent.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by ./liblagent.so)
./liblagent.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by ./liblagent.so)
        linux-vdso.so.1 =>  (0x00007fff8d36a000)
        libjawt.so => /x/opt/oracle/oracle-jdk-7u45-linux-x64/jdk1.7.0_45/jre/lib/amd64/libjawt.so (0x00002ba2e0abe000)
        libjvm.so => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ba2e0cd1000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002ba2e0ed5000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ba2e11d6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002ba2e1459000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ba2e1667000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ba2e1884000)
        libawt.so => /x/opt/oracle/oracle-jdk-7u45-linux-x64/jdk1.7.0_45/jre/lib/amd64/libawt.so (0x00002ba2e1bdd000)
        libmawt.so => not found
        libjava.so => /x/opt/oracle/oracle-jdk-7u45-linux-x64/jdk1.7.0_45/jre/lib/amd64/libjava.so (0x00002ba2e1eb0000)
        /lib64/ld-linux-x86-64.so.2 (0x00002ba2e0695000)
        libjvm.so => not found
        libjvm.so => not found
        libjvm.so => not found
        libverify.so => /x/opt/oracle/oracle-jdk-7u45-linux-x64/jdk1.7.0_45/jre/lib/amd64/libverify.so (0x00002ba2e20dd000)
        libjvm.so => not found


Could you please review and advice whether glibc version is essential and any other lib files are missing

Thanks
Sattish.

**Comment by RichardWarburton** [comment]
Hi @sattishv - it looks like you're trying to build with Java 7. Java 8 is required.

**Comment by sattishv** [comment]
Hi Richard,

Thanks for the response. Is it possible to use the agent without building it like referencing the lib file in jvm startup options as java.library path. If its a jar we hook the jar through javaagent options. We are quite curious to use this profiler. please suggest us.

Thanks
Sattish.

**Comment by RichardWarburton** [comment]
Hi @sattishv,

You can download it from http://insightfullogic.com/honest-profiler.zip and run it using the following instructions: https://github.com/RichardWarburton/honest-profiler/wiki/How%20to%20Run.

**Comment by sattishv** [comment]
Hi richard,

Thanks a lot for the link. Attaching a java agent to JVM would be ideal for our environment. Let me try to configure and share the findings. Appreciate your support.

Thanks
Sattish
