### ISSUE TITLE
report native and mixed mode (i.e., Java + native) stack frames

### ISSUE THREAD

**Issue by ceeaspb** [RichardWarburton/honest-profiler#127]
Recent changes last year to the jvm fixed up frame pointers so that native stack frames / whole stack could be walked.
Jeremy Manson reported that google had this working previously in LJP.

Some workloads spend a lot of time in kernel for whatever reason, by extending HP to native and mixed mode stacks this could extend the field of vision for HP.

**Comment by nitsanw** [comment]
My 2c:
Adding full stack walking capabilities is a large problem to solve (it is solved elsewhere by perf+PMA for Unix users, but that has further issues, and with Solaris Studio with other issues) and I'm not sure this is the place to solve it.

**Comment by nitsanw** [comment]
@RichardWarburton close as WONTFIX?

**Comment by RichardWarburton** [comment]
That's probably fair.
