### ISSUE TITLE
Make kMaxFramesToCapture constant passed into AGCT a configurable profiler parameter

### ISSUE THREAD

**Issue by melix** [RichardWarburton/honest-profiler#131]
Hi,

I've been using honest profiler pretty intensively for the past few weeks and I must say it's a pretty awesome tool, great job! I'm using the `FlameGraphDumperApplication` to generate a log file that can be fed to `FlameGraph.pl`, which generates the nice searchable SVGs for me. However, I noticed something weird, like in the picture below:

![wut](https://cloud.githubusercontent.com/assets/316357/15251894/ce91fdac-192b-11e6-9f8f-66ac3ed42d61.png)

You can see that I have calls to `DaemonCommandExecution.proceed`, and those are visible at different "heights" in the graph. But this is just plain wrong. They should be all found at the same level, which tells be that the call stack was truncated.

At first, I blamed the export tool and tried to debug it, but I can see that if it was parsing the file wrong, it would probably end up throwing an exception. Nevertheless, I have attached a file that is the actual result of a profile session, and causes the problem.

[hp.log.zip](https://github.com/RichardWarburton/honest-profiler/files/263512/hp.log.zip)

It seems to happen very frequently when stack frames are big, which is, for various reasons, unfortunately my case. For simple cases I can "reconstruct" the missing parts of stack frames, but it's time consuming and error prone.

Any idea what could be going on?

**Comment by melix** [comment]
(To be clear, the issue is visible on the left and right of this picture, where those bars actually "belong" to the middle)

**Comment by nitsanw** [comment]
We currently have a default value to the max number of frames in the stack which is used in the call to AGCT here:

		  (*asgct)(&trace, kMaxFramesToCapture, context);

The value is defined here:

    // Things that should probably be user-configurable
    // Maximum number of frames to store from the stack traces sampled.
    static const int kMaxFramesToCapture = 128;

As the comment suggests, it should probably be configurable...

**Comment by melix** [comment]
Awesome, that was it! I rebuilt the agent and now I have full call stacks, thanks!

**Comment by nitsanw** [comment]
Cool, I'll re-purpose this ticket as a reminder to fix this

**Comment by nitsanw** [comment]
@melix thanks for reporting, and if you have the time and initiative to crack this issue in a PR that would be awesome :-)

**Comment by melix** [comment]
I can change a hardcoded constant in a C file. Going beyond is going to involve a bit more, since I haven't touched such code for what, 15 years? :D

**Comment by ikavalio** [comment]
Hi @nitsanw, @melix 

I currently have the same issue with truncated traces, so I decided to make kMaxFramesToCapture configurable parameter. I've implemented it naively and tested locally, but not sure if it's ready for PR since C++ is not my strong suit. Could you please take a brief look into my changes https://github.com/RichardWarburton/honest-profiler/compare/master...ikavalio:master just to make sure I'm heading in the right direction.

**Comment by nitsanw** [comment]
Closing, fixed by #151
