### ISSUE TITLE
Print warning if -XX:+DebugNonSafepoint is not enabled

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#132]
When not enabled the profile we take is operating on far less information, resulting in a profile bias toward debug info existence. This is very similar to safepoint bias in it's effect.

**Comment by phraktle** [comment]
+1. For reference, the full param is ```-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints```

**Comment by nitsanw** [comment]
This is now no longer required as the agent effectively enables the option by itself with #133.
