### ISSUE TITLE
bottom-up visualization

### ISSUE THREAD

**Issue by phraktle** [RichardWarburton/honest-profiler#134]
Hi,

It would be nice to be able to produce bottom-up call trees (and the corresponding flamegraph exports). Is there a feature for this already that I missed?

Thanks,
  Viktor

**Comment by nitsanw** [comment]
I'm not sure what you mean, can you give an example?

**Comment by phraktle** [comment]
The purpose is to identify hot methods and trace backwards to the various callers (rather than going from callers to callees, as is the case now).

**Comment by nitsanw** [comment]
@phraktle got it, never seen that done as flame graphs. Interesting notion.

**Comment by ceeaspb** [comment]
@phraktle @nitsanw I think what you are describing is an "Icicle Graph" which is a reverse inverted flamegraph, atleast in flamegraph terminology.

https://github.com/brendangregg/FlameGraph
--reverse     # generate stack-reversed flame graph

--inverse (icicle graph) then displays the reverse stacks upside down so the call stacks appear in the same vertical order as they would without reverse.

It can be useful to see the aggregated cost of a function/method that is called in lots of different calls stacks.

**Comment by phraktle** [comment]
@ceeaspb Thanks, flamegraph --reverse does the trick! That's enough for my purposes, though you may want to consider supporting this in honest-profiler as well.
