### ISSUE TITLE
Do you accept donations?

### ISSUE THREAD

**Issue by cubuspl42** [RichardWarburton/honest-profiler#135]

**Comment by RichardWarburton** [comment]
dotations?

**Comment by cubuspl42** [comment]
@RichardWarburton Don't be picky :octopus:

**Comment by RichardWarburton** [comment]
Ahh, my bad. Tired when I read it at first ;)

I hadn't thought of donations at all to be honest. What kind of thing did you have in mind? A one-off donation, or a patreon style $x/month?

**Comment by cubuspl42** [comment]
One-off, I guess

**Comment by RichardWarburton** [comment]
I've had a think about it and I won't take donations at the moment. Hopefully I'll have more time to allocate to Honest Profiler soon and then I could accept money without feeling guilty ;)
