### ISSUE TITLE
Can't find libawt.so

### ISSUE THREAD

**Issue by maseev** [RichardWarburton/honest-profiler#147]
Hi.

I've been trying to run my application with honest-profiler agent recently, but I constantly get the following error during the JVM initialization:

> Error occurred during initialization of VM
Could not find agent library /home/maseev/tools/other/honest-profiler/liblagent.so in absolute path, with error: libawt.so: cannot open shared object file: No such file or directory

At first, I thought that the problem was in the libawt.so library itself, because it didn't exist. But then I run the find shell command:

```
maseev@evilmachine:~$ find /home/maseev/tools/lang/jdk1.8.0_92/ | grep "libawt.so"
/home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libawt.so
```

My JAVA_HOME environment variable points to the same folder where the libawt.so library is located:

```
maseev@evilmachine:~$ $JAVA_HOME
bash: /home/maseev/tools/lang/jdk1.8.0_92: Is a directory
```

I even added another environment variable how it was suggested in this [issue](https://github.com/RichardWarburton/honest-profiler/issues/105).

```
maseev@evilmachine:~$ $LD_LIBRARY_PATH
bash: /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/: Is a directory
```

But it didn't help at all.

My OS description:

```
Linux evilmachine 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Am I missing something? Are there any additional steps I have to perform in order to run honest-profiler?

Thanks.

**Comment by maseev** [comment]
It looks like that the liblagent.so has some unsatisfied shared dependencies:

```
maseev@evilmachine:~/tools/other/honest-profiler$ ldd liblagent.so 
	linux-vdso.so.1 =>  (0x00007ffdb7df8000)
	libjawt.so => /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libjawt.so (0x00007f062351f000)
	libjvm.so => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f062331b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0623017000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0622d11000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0622afb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06228dd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0622518000)
	libawt.so => /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libawt.so (0x00007f0622246000)
	libawt_xawt.so => /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libawt_xawt.so (0x00007f0621fed000)
	libjava.so => /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libjava.so (0x00007f0621dc1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f062392a000)
	libjvm.so => not found
	libjvm.so => not found
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f0621baf000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f062187a000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f0621670000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f062146a000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f062125a000)
	libjvm.so => not found
	libjvm.so => not found
	libverify.so => /home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/libverify.so (0x00007f062104b000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f0620e2c000)
	libjvm.so => not found
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f0620c28000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f0620a22000)
```

In particular, it can't find this library - libjvm.so. According to file this library does exist:

```
maseev@evilmachine:~/tools/other/yjp-2016.02/bin/linux-x86-64$ find /home/maseev/tools/lang/jdk1.8.0_92/ | grep "libjvm.so"
/home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/server/libjvm.so
```

**Comment by teichert** [comment]
I ran into this yesterday, too.  After discovering the libraries that weren't found (using `ldd` as you did) and after find where there were on my system (btw `locate libjvm.so` works well for that), I did something like the following to add them to the library path (I'm using bash):

`export LD_LIBRARY_PATH="/home/maseev/tools/lang/jdk1.8.0_92/jre/lib/amd64/server:${LD_LIBRARY_PATH}"`

Things worked for me after that (I actually was missing two libraries). I also added that line to my .bash_profile to make it automatic.

**Comment by maseev** [comment]
It actually did the trick. Now I'm able to run my application with the honest-profiler agent. Thanks @teichert!

@RichardWarburton I think It would be great to add this information to the project's wiki. WDYT?

**Comment by RichardWarburton** [comment]
I'm happy to add the information. I just want to test it out first ;)

**Comment by ikavalio** [comment]
Hi. I faced the same issue on machine where some of libjawt.so dependencies were not met and couldn't be installed (i.e. libXext.so). I solved it by patching liblagent.so and removing libjawt.so from dynamic dependencies (https://github.com/NixOS/patchelf). Everything worked just fine after that. I guess AWT dependency is not required to build agent but CMake findJNI appends awt*.so to JNI_LIBRARIES. If you set JNI_LIBRARIES explicitly (to libjvm.so only) in CMakeLists.txt, shared library will be linked correctly.

**Comment by ajaygeorge** [comment]
Thanks @ikavalio . Using patchelf helped me resolved this issue.

**Comment by hube** [comment]
I ran into this issue and the solution suggested by @maseev in his [July 8 comment](https://github.com/RichardWarburton/honest-profiler/issues/147#issuecomment-231465367) worked for me

**Comment by ackhare** [comment]
Please help I am facing the same issue 
How to use patchelf @ajaygeorge

**Comment by ackhare** [comment]
I was able to do 
The command will be 
patchelf --remove-needed libjawt.so /home/chetan/Downloads/honest-profiler/liblagent.so

Thanks @ajaygeorge @ikavalio

**Comment by RichardWarburton** [comment]
I've just investigated this issue this afternoon and for me libjawt.so isn't required for me. Is this an issue that is specific to a certain JVM version or is it Mac specific or something?

**Comment by ikavalio** [comment]
@RichardWarburton, when I'm compiling agent from scratch under Ubuntu 16.10 it's not added as a dependency, however cmake includes libawt to JNI_LIBRARIES variable. Under El Capitan libawt is not added as a dependency as well.

I think it is an issue of old .so library and the way it was linked.

**Comment by RichardWarburton** [comment]
@ikavalio my apologies for being dumb here, but I'm not sure whether the issue is fixed for you or not? If it's not fixed, is there any chance you can just list how to reproduce the problem or on what platform it occurs?

**Comment by ikavalio** [comment]
@RichardWarburton, no problem at all. I couldn't reproduce the problem on any machine/platform available to me (both OS X and Linux, clang++ and gcc).

**Comment by ChrisLancs** [comment]
A solution I found to work generally may not work in this case is worth a try, at the worst it will make no difference, at best it will fix the issue you have.

Find the path you want to the link applying to (/usr/lib/ as below is common, but may not show in your properties output, adjust this part to reflect one that is shown by the following command, if there is one that has java in the path you may use that for sake of keeping things together but /usr/lib would work just as well if available.)
$ java -XshowSettings:properties

Find the location of any existing libjawt.so and use its path in the place of <path>
$ locate libjawt.so

make the link.
$ sudo ln -s <path>/libjawt.so /usr/lib/libjawt.so

Run your application again, should resolve the dependency.

All you need is locate libjawt.so and use one of the results as the path/to.

This was mine under *Ubuntu18.04 with openjdk 11 installed but yours may be different, just "locate" it and you should be set.

With this there is no need to 
add anything to the environment or bashrc as its already pulled in.
