### ISSUE TITLE
-agentpath options: "host" and "port" don't work for me

### ISSUE THREAD

**Issue by RobLuckePuppet** [RichardWarburton/honest-profiler#148]
The binary blob (.zip) on your website, listed as "download binary here" doesn't match the current state of the repository.  Things didn't work for me until I completely rebuilt from scratch (i.e. the "host" and "port" options to the agent)

**Comment by RobLuckePuppet** [comment]
The system is CentOS 7, selinux disabled (which can affect socket allocation), 
3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux, latest version of honest-profiler from .zip file.  I've debugged this to death.  The parameters are showing on the JVM command line.

**Comment by RichardWarburton** [comment]
I think the fix for this issue is to build a new honest profiler binary.
