### ISSUE TITLE
Question: Behavior difference between OS X and Linux

### ISSUE THREAD

**Issue by chhsiao90** [RichardWarburton/honest-profiler#150]
I had run the simplest sample but there is some difference between this two OS.
More specific, I think there is some problem on my linux environment.

First, I will provide my env and sample code

               |OS X                                 |Linux
-------- |-------------------------|-----------------------------
OS         |OS X El Capitan 10.11.6   | Debian GNU/Linux 8 (jessie)
JDK       |oracle64-1.8.0_65           |oracle64-1.8.0.101
HP         |Latest build from github |Latest build from github

```java
public class Test {
    public void run() {
        for (int i = 0; i < 100; i++) {
            exec();
        }
    }

    private void exec() {
        System.out.println("test");
    }

    public static void main(String[] args) {
        new Test().run();
    }
}
```

Then I compile and run in both environment
```shell
javac Test.java
java -agentpath:liblagent.so -cp . Test # In Linux
java -agentpath:liblagent.dylib -cp . Test # In OS X
```

On my OS X, the agent help me to collect the statistic in a log named log-$pid-$timestamp.hpl
But in Linux, a log file log-$pid-$timestamp.hpl had bean created without any data in it.

Is it my environment's problem?
Thanks!

**Comment by RichardWarburton** [comment]
Well, I and many other people have run HP on linux, so its unlikely to be a direct bug where it runs on Mac OS but not Linux. My best guess at this issue would be that on linux that the program completes and exits before any samples are taken or before the background thread in the profiler has a chance to write them down to disk. It may be slower on your Mac OS environment - maybe more programs running in the background or something.  Your program in question doesn't do very much and may well execute quickly enough to do so. I would replace 100 with 10,000 and see if you get some samples recorded.

**Comment by chhsiao90** [comment]
Got it, it seams that my environment had some problem that caused HP had some unexpected behavior. I will keep trying on it. Thanks for your feedback!
