### ISSUE TITLE
does anyone have a up-to date binary? 

### ISSUE THREAD

**Issue by chengxiayan** [RichardWarburton/honest-profiler#180]
The binary blob (.zip) on the website, listed as "download binary here" doesn't match the current state of the repository. does anyone have an up-to date binary? I have tried to build myself, but  I was blocked by some problems

**Comment by PhRX** [comment]
Hi @chengxiayan, I can get you a build, created on Linux Mint. I'll need some way to get it to you though...

**Comment by ceeaspb** [comment]
Hi @chengxiayan please describe what the problems were so they can be looked at and possibly fixed/eliminated

**Comment by chengxiayan** [comment]
Hi , PhRX, my email is  chengxiayan@gmail.com，thanks. I am using honest profiler on Centos 6.4 , and i need the function of TCP to start or stop profiling dynamically. The binnary on the website looks like do not support that function.  I have recompiled it successfully, but it require GLIB_C2.14 to run, which is higher than GLIBC_2.12 on Centos.  so i tried to compile it with gcc 4.47, unfortunately, compile need c++ 11,which gcc 4.47 can not fully support. so my problem is that how i can run honest profiler with the function of TCP on Centos 6.4 which only has GLIB_C2.12

**Comment by chengxiayan** [comment]
Maybe I can recompile honest profiler with gcc 4.47 after delete the features of c++ 11, but it looks complicated.

**Comment by PhRX** [comment]
I've (finally) sent a binary to @chengxiayan.

**Comment by sandermvdb** [comment]
Could you also please sent the binary to me? Or post it (64 bit version) somewhere on the internet? Tx.

**Comment by PhRX** [comment]
If you can get your e-mail address to me I'd be happy to.

**Comment by sandermvdb** [comment]
How can I do that without making it public?

**Comment by PhRX** [comment]
My problem exactly too :/ Shame github doesn't seem to support private messages. I'll have a think about it.

**Comment by RichardWarburton** [comment]
As a temporary solution I've uploaded a build of the result of @PhRX 's PR at http://insightfullogic.com/honest-profiler.zip. Hopefully this should aid in testing #184 and resolve this issue.

Once we've gotten through the PR and everything is merged I'll get some kind of CI process up and running.

**Comment by PhRX** [comment]
Thanks @RichardWarburton ! Much appreciated !

On Fri, Feb 10, 2017 at 2:39 PM, Richard Warburton <notifications@github.com

**Comment by sandermvdb** [comment]
Maybe a stupid question, but does this run under Windows? I guess it needs to be compiled for it...?

**Comment by PhRX** [comment]
No, the agent can only be compiled for Linux, Mac OSX or FreeBSD. Not sure
what platform the zip Richard provided was compiled on, but it certainly
isn't Windows.

**Comment by RichardWarburton** [comment]
I compiled it on Ubuntu 16.04. The binary won't work under windows.
