### ISSUE TITLE
Is it possible attaching agent on the fly?

### ISSUE THREAD

**Issue by serkan-ozal** [RichardWarburton/honest-profiler#182]
Hi,

Maybe this is dump question, 

Is it possible implementing `Agent_OnAttach` in the `agent.cpp` and supporting hones-profiler agent attaching on the fly via `VirtualMachine::loadAgentPath(String agentPath, String options` programmatically?

As far as I see, the required capabilities by the honest-profiler are also available at live phase if I am not missing something. Can you verify it?
 
https://github.com/RichardWarburton/honest-profiler/blob/master/src/main/cpp/agent.cpp#L105

``` c
    caps.can_generate_all_class_hook_events = 1;

    caps.can_get_source_file_name = 1;
    caps.can_get_line_numbers = 1;
    caps.can_get_bytecodes = 1;
    caps.can_get_constant_pool = 1;
    caps.can_generate_compiled_method_load_events = 1;
#ifdef GETENV_NEW_THREAD_ASYNC_UNSAFE
    caps.can_generate_native_method_bind_events = 1;
#endif
```

Regards.

**Comment by RichardWarburton** [comment]
Hi, it should be possible. Issue #22 is supposed to track the implementation of this feature.
