### ISSUE TITLE
Allow for a different unittest path

### ISSUE THREAD

**Issue by rombert** [RichardWarburton/honest-profiler#21]
I've had to make the following change to the Makefile on OpenSUSE 13.1 to convince make-test to run:

```
diff --git a/Makefile b/Makefile
index 384cfe1..37afa37 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ COPTS:=$(PLATFORM_COPTS) $(CXX_COPTS) $(GLOBAL_COPTS) $(PLATFORM_WARNINGS) \
 # TODO: consider re-adding in production -fno-exceptions
 
 INCLUDES+=-I /usr/include/i386-linux-gnu/c++/4.8/ -I$(JAVA_HOME)/$(HEADERS) -I$(JAVA_HOME)/$(HEADERS)/$(UNAME) 
-TEST_INCLUDES=$(INCLUDES) -I/usr/include/unittest++
+TEST_INCLUDES=$(INCLUDES) -I/usr/include/unittest-cpp
 
 # LDFLAGS+=-Wl,--export-dynamic-symbol=Agent_OnLoad

**Comment by RichardWarburton** [comment]
@rombert have you tried deleting `CMakeCache.txt` and re-running `cmake CMakeLists.txt`?

**Comment by rombert** [comment]
@RichardWarburton - thanks, but that still did not help.

**Comment by RichardWarburton** [comment]
@rombert I've added parameters for this for you. For example on ubuntu you would write the following to manually set UnitTest++:

`UNITTEST_INCLUDE_DIRS="/usr/include/unittest++/" UNITTEST_LIBRARIES="UnitTest++" cmake CMakeLists.txt`

If nothing appears to be different, try cleaning the cache - `rm -rf CMakeCache.txt CMakeFiles/`

**Comment by rombert** [comment]
UNITTEST_INCLUDE_DIRS="/usr/include/unittest-cpp" UNITTEST_LIBRARIES="UnitTest++" cmake CMakeLists.txt 

worked for me, thank you!
