### ISSUE TITLE
Ability to interactively start and stop the profiler

### ISSUE THREAD

**Issue by RichardWarburton** [RichardWarburton/honest-profiler#6]

**Comment by mbarbon** [comment]
I'm working on a patch for this (I added a com.insightfullogic.honest_profiler.core.control.Agent class with start/stop methods and a start=0|1 (defaults to 1) parameter for the agent).

I will send a pull request as soon as I finish writing the tests.

**Comment by RichardWarburton** [comment]
Fantastic - would be a great addition.

**Comment by nitsanw** [comment]
This is already implemented in PR #119
