### ISSUE TITLE
Add text view of log

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#72]
To aid in debugging and compensate for any missing views.

**Comment by RichardWarburton** [comment]
This this functionality should already be offered by the command line client. Is there anything that's missing?

**Comment by nitsanw** [comment]
I'm refering to a text conversion of the log contents rather than text view of the collected profile results. I've hacked something together and will send a PR soon.

**Comment by RichardWarburton** [comment]
Ahh. That would make debugging easier and i would appreciate the pr. It
should be easy to implement something that piggybacks onto logparser and
implement logeventlistener.

**Comment by RichardWarburton** [comment]
Fixed by @nitsanw 's PR the other day.
