### ISSUE TITLE
Thread local JNIEnv allocates, which is not allowed in a signal handler

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#75]
This is a serious issue as I found when the signal handler trigger while in malloc resulting in the following stack trace:
 #0  0x00000031f98f80ae in __lll_lock_wait_private () from /lib64/libc.so.6
 #1  0x00000031f987d35b in _L_lock_9495 () from /lib64/libc.so.6
 #2  0x00000031f987a946 in malloc () from /lib64/libc.so.6
 #3  0x00000031f94110d0 in tls_get_addr_tail () from /lib64/ld-linux-x86-64.so.2
 #4  0x00000031f94115a0 in __tls_get_addr () from /lib64/ld-linux-x86-64.so.2
 #5  0x00007fed0ade8134 in CurrentJniEnv () at /root/git/honest-profiler/src/main/cpp/globals.h:162
 #6  Profiler::handle (this=0x19ab8b0, signum=<optimized out>, info=<optimized out>, context=0x4400045fc400) at /root/git/honest-profiler/src/main/cpp/profiler.cpp:103
 #7  <signal handler called>
 #8  0x00000031f98e54f7 in mprotect () from /lib64/libc.so.6
 #9  0x00000031f987a3ab in _int_malloc () from /lib64/libc.so.6
 #10 0x00000031f987a951 in malloc () from /lib64/libc.so.6

This led to the JVM hanging in one run out of 10 or so randomly, depending on load on the box etc.
In the comments in globals.h we have:

      // This is very dangerous.  __thread is not async-safe when used in
      // a shared library, because it calls malloc the first time a given
      // thread accesses it.  This is unlikely to cause problems in
      // straightforward Java apps, but a real fix involves either a fix
      // to glibc or to the Java launcher, and casual users will have a
      // hard time with this.
      static __thread JNIEnv
      *
      env_;

This is from original J.Manson implementation.

**Comment by nitsanw** [comment]
Fixed up locally by following the method described here for gaining access to JNIEnv:
http://stackoverflow.com/questions/12900695/how-to-obtain-jni-interface-pointer-jnienv-for-asynchronous-calls
Tested the new build and it seems to work and not hang, joy for all! Will be sending a PR.

**Comment by RichardWarburton** [comment]
Thanks!

**Comment by RichardWarburton** [comment]
Fixed by PR #74
