### ISSUE TITLE
How does the memory ordering in the MPSC circular queue work

### ISSUE THREAD

**Issue by RajivSignal** [RichardWarburton/honest-profiler#76]
The MPSC queue might have some race conditions.

From https://github.com/RichardWarburton/honest-profiler/blob/master/src/main/cpp/circular_queue.cpp
```cpp
bool CircularQueue::push(const JVMPI_CallTrace &item) {
    size_t currentInput;
    size_t nextInput;
    do {
        currentInput = input.load();
        nextInput = advance(currentInput);
        if (output.load() == nextInput) {
            return false;
        }
        // TODO: have someone review the memory ordering constraints
    } while (!input.compare_exchange_strong(currentInput, nextInput,
            std::memory_order_release,
            std::memory_order_relaxed));
    // My comment: The reader could be already reading this frame since the CAS succeeded.
    write(item, currentInput);

    return true;
}
```

So the producer has a while loop doing CAS operations till it succeeds. After that it does a plain write of the slot that it just claimed.

```cpp
void CircularQueue::write(const JVMPI_CallTrace &trace, const size_t slot) {
    JVMPI_CallFrame *fb = frame_buffer_[slot];
   // My comment: Reader could already be reading at this point.
    for (int frame_num = 0; frame_num < trace.num_frames; ++frame_num) {
        // Make sure the padding is all set to 0.
        safe_reset(&(fb[frame_num]), sizeof(JVMPI_CallFrame));

        fb[frame_num].lineno = trace.frames[frame_num].lineno;
        fb[frame_num].method_id = trace.frames[frame_num].method_id;
    }

    buffer[slot].frames = fb;
    buffer[slot].num_frames = trace.num_frames;
    buffer[slot].env_id = trace.env_id;
}
```

This write itself has no release operation as far as I can tell. So you first claim a slot through CAS (which itself does a fence) but there is no fence after the write. In fact the reader thread could be reading the contents of the frame that is still being written to.

While reading:
```cpp
bool CircularQueue::pop() {
    const auto current_output = output.load();

    // queue is empty
    if (current_output == input.load()) {
        return false;
    }

    listener_.record(buffer[current_output]);
    output.store(advance(current_output));
    return true;
}
```

We just do a strongly consistent load of the output index. But we don't wait to see if the producer is still in the middle of writing to the frame. We just feed it to the listener_ and the frame could be in any intermediate state including a partial memset to 0 (through the ```safe_reset``` function, which btw I wouldn't count on. Compilers could detect this pattern and actually use a ```memset``` instead). Seems like the ```listener_``` is some how expected to deal with the partially set Frame. Actually I think it can never be certain when the Frame has been written to since there is no write barrier after writing the frame, unless the ```env_id``` field write somehow involves a barrier and the ```listener_``` is expected to first perform a load of that ```env_id``` before reading the rest.

Another possible implementation:  The frame struct can be contained in another struct that has  a single atomic field (in addition to the Frame struct), which you can then do a release operation (say set to 1) on the producer(s) after the write of the Frame's fields. Then on the single consumer, once it sees that there is an event(container with Frame) it should first spin on the release_field till it is 1. Then it knows that the entire Frame has been written into and it can then pass on the Frame pointer to the listener to consume synchronously. After the listener is done, the consumer can then set that release_field to 0, before incrementing ```output```. So basically there is an additional field in the ring buffer entries that can be used for release/acquire barriers (set to 1 on producers, set to 0 on consumers) in addition to the CAS operation that is needed to claim a slot.

**Comment by RichardWarburton** [comment]
https://github.com/RichardWarburton/honest-profiler/commit/d19c61b3d9b5c37e67fc0ce0812d6b6d8dc20857 should fix this issue. In your text you said add a release flag for each Frame - but I think you really want one for the whole stack trace entry, since that's what the should be trying to atomically commit to the ring buffer.

I'm going to close this issue, but if there's a bug in my fix, then feel free to reopen.

**Comment by RajivSignal** [comment]
I mean't the whole stack trace entry. The patch looks correct to me. Thanks for the fix.
