### ISSUE TITLE
Safe_reset function can be optimized to memset

### ISSUE THREAD

**Issue by RajivSignal** [RichardWarburton/honest-profiler#77]
The safe_reset function in the ring buffer is designed to avoid ```memset.``` As I understand you don't want to use ```memset``` in the producer, because it is not async safe. Here is g++'s output: 

http://goo.gl/V4oL1K

In my experience compilers are very aggressive in reducing such patterns to more optimized memset, memcpy implementations. I think the best option is to choose an algorithm that does not do a memset like operation on the producer at all. #46 outlines one such approach.

**Comment by RichardWarburton** [comment]
@RajivSignal Thanks for spotting this. I don't quite get your reference to #46 outlining a solution. Do you mean #76?

**Comment by RajivSignal** [comment]
Sorry mean't #76.

**Comment by RajivSignal** [comment]
I meant to say that the memset like function or memset itself can be called on the consumer after feeding each record to the ```listener_``` recording each entry. That way when the producer gets the record it can be sure that it is completely clean. So on the consumer things would look a bit like this:
```cpp
bool CircularQueue::pop() {
    const auto current_output = output.load();

    // queue is empty
    if (current_output == input.load()) {
        return false;
    }

    // wait until we've finished writing to the buffer
    while(buffer[current_output].is_committed.load() != COMMITTED) {
        usleep(1);
    }

    listener_.record(buffer[current_output].trace);

    // My comment - additionally zero out all the traces.
    JVMPI_CallFrame *fb = frame_buffer_[current_output];
    auto num_frames = buffer[current_output].trace.num_frames
    for (int frame_num = 0; frame_num < num_frames; ++frame_num) {
      // Make sure the padding is all set to 0.
      safe_reset(&(fb[frame_num]), sizeof(JVMPI_CallFrame));
    }
    buffer[current_output].is_committed.store(UNCOMMITTED);
    output.store(advance(current_output));
    return true;
}
```

And on the producer:
```cpp
// Unable to use memcpy inside the push method because its not async-safe
void CircularQueue::write(const JVMPI_CallTrace &trace, const size_t slot) {
    JVMPI_CallFrame *fb = frame_buffer_[slot];
    for (int frame_num = 0; frame_num < trace.num_frames; ++frame_num) {
        // My comment: All of the padding is already  set to 0, because the consumer has zeroed it out.
        // We don't need to risk writing memset like functions in an async context.
        safe_reset(&(fb[frame_num]), sizeof(JVMPI_CallFrame));

        fb[frame_num].lineno = trace.frames[frame_num].lineno;
        fb[frame_num].method_id = trace.frames[frame_num].method_id;
    }

    buffer[slot].trace.frames = fb;
    buffer[slot].trace.num_frames = trace.num_frames;
    buffer[slot].trace.env_id = trace.env_id;
    buffer[slot].is_committed.store(COMMITTED);
}
```

**Comment by RichardWarburton** [comment]
Hi Rajiv,

I've applied your suggestion in order to move the clearing of the buffer to the consumer.

**However** `safe_reset` is also used in the `Profiler::handle` method where it also needs to be async-safe. At the moment this isn't a problem because GCC doesn't optimise `safe_reset` to `memset` when using using -O2, which is what honest-profiler is currently set to use. So I'm going to close the issue.

I don't like how brittle the code is to compiler optimisations though and if you have any suggestions on an alternative implementation of safe_reset that /can't/ be optimised that would be great. I've also pushed a patch that adds `-fno-tree-loop-distribute-patterns` which is the compiler flag that should stop the memset optimisation from happening even if we bump the optimisation level to -O3.

**Comment by RajivSignal** [comment]
It is really annoying when GCC decides to take it upon itself to do something this radical. I didn't know about the ```-fno-tree-loop-distribute-patterns``` flag. Thanks for the tip. Though it is sad that one has to throw out the baby with the bath water, because it means that other places that would benefit from these optimizations have to also forgo them. I wish GCC etc allowed users to make these decisions at call site instead of globally </rant>.
