### ISSUE TITLE
Documentation should mention that CMake requires JAVA_HOME to be defined

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#86]
The CMake error when this is not the case is not entirely useless, but may still confuse people:
    
    CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
      Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
      JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
    Call Stack (most recent call first):
      /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake-3.0/Modules/FindJNI.cmake:286 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:29 (find_package)

**Comment by nitsanw** [comment]
Fixed wiki

**Comment by RichardWarburton** [comment]
Thanks!
