### ISSUE TITLE
Add build instructions to repository

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#87]
The build instructions are on the wiki
This would make the "pull & build" workflow slightly less awkward IMO.

**Comment by RichardWarburton** [comment]
Hmm, I do wonder about things like this. Would a directly url link to the "how to build" section of the wiki not be better? Otherwise I have to keep the documentation updated in two separate places.

**Comment by RichardWarburton** [comment]
I've decided to just put a "how to build" link rather than have to maintain two copies of the docs.
