### ISSUE TITLE
Add instructions for running the C++ unit tests

### ISSUE THREAD

**Issue by nitsanw** [RichardWarburton/honest-profiler#91]
Current doc recommends users/contributors skip the tests, surely that is not a good plan?
I'm currently struggling to get the C++ tests working on my machine, but that is perhaps a separate issue.

**Comment by RichardWarburton** [comment]
I've added the https://github.com/RichardWarburton/honest-profiler/wiki/How-to-build#how-to-run-tests entry into the documentation. Feel free to re-open this ticket if you think I've missed anything.
