### ISSUE TITLE
Add sample error rates to the UI

### ISSUE THREAD

**Issue by RichardWarburton** [RichardWarburton/honest-profiler#97]
including a recommendation to  `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` to get best information.

**Comment by ceeaspb** [comment]
Assuming you mean error in terms of no java stack frames returned,
I think this would be useful for 2 reasons:
1) if the sample error rate is high then there is a lot of cpu time "doing other stuff" so the reported stacks may be a small %age of the overall cpu cost. eg. "100%" is really 5%...
2) the errors could be broken down into some useful categories in the lightweight java profiler's enum CallTraceErrors

**Comment by nitsanw** [comment]
Regarding https://github.com/RichardWarburton/honest-profiler/issues/97#issue-114650050 I think we should file a separate ticket for the agent to detect if the flag is set and print a warning when it isn't.
I've given the issue of failed samples some thought and I think we should handle this differently than printing error rates. The error rates are too easy to miss, as the users eyes go to the call-tree/flat profile. I think it is better if we assign each error a mock method ID and report them as frames. This way they would feature front and centre in the profile and in the right context intuitively. This is similar to the way 'unknown' frames are shown in perf top for instance.
A PR is coming.

**Comment by RichardWarburton** [comment]
I like the idea. Are you planning on having multiple mock frames, or just one aggregating all the unknowns? I would slightly prefer one aggregating all the unknowns that you can then click on to expand the details. Progressive disclosure and all that jazz. I'm happy to have my mind changed if you have a good reason to go the other way.

**Comment by nitsanw** [comment]
I think it's easier to report them separately + it is likely that a particular error is behind most of the failed samples, so the drill down is unlikely to expand into something informative. I'm not sure what you mean by progressive disclosure though, and perhaps my UX skillz ain't that mad.

**Comment by RichardWarburton** [comment]
Ok, let's go with separate to begin with and see how it works out.

Progressive Disclosure = don't throw too much information at the user in one go as its confusing.

**Comment by nitsanw** [comment]
The users mustn't grumble so much. Add a further feature to match remedial alcoholic drinks to profiles. "Consume this profile with a glass of port and some cheese" "This profile best enjoyed with single malt whiskey, make it a double". This is also an opening to sponsorship from breweries and distilleries and a profiling tour of Scotland.

**Comment by ceeaspb** [comment]
Sounds great @nitsanw thanks. It's a profiling rebellion (the name of brewery at the end of my road)!

The key here is to ensure that the user isn't fooled into thinking that 100% of java stack samples is 100% of the cpu that the java process is using.

Mock frames sounds good.

It turns out that some of the "errors" aren't errors at all ! So reporting them as what they are rather than errors would make more sense to end users - ie. mock frame "time in GC" (as far as jvmti reported eg. -2 GcTraceError) etc.

**Comment by nitsanw** [comment]
Sample output before fix:

    Flat Profile (by method):
	(t  6.3,s  4.5) psy.lob.saw.ProfilingBenchmarks.hashMapPutIsToBlame
	(t  1.7,s  1.7) java.util.HashMap.putVal
	(t  0.8,s  0.6) psy.lob.saw.ProfilingBenchmarks.prepare
	(t  5.8,s  0.2) psy.lob.saw.generated.ProfilingBenchmarks_hashMapPutIsToBlame_jmhTest.hashMapPutIsToBlame_avgt_jmhStub
	(t  0.5,s  0.2) java.lang.ClassLoader.defineClass1
	(t  0.1,s  0.1) java.util.HashMap.hash
	(t  0.4,s  0.1) org.openjdk.jmh.runner.link.BinaryLinkClient.<init>
	(t  0.1,s  0.1) sun.misc.Unsafe.park
After fix:

    Flat Profile (by method):
	(t 80.8,s 80.8) AGCT::Unknown Java[ERR=-5]
	(t 10.0,s 10.0) AGCT::Unknown not Java[ERR=-3]
	(t  6.3,s  4.5) psy.lob.saw.ProfilingBenchmarks::hashMapPutIsToBlame
	(t  1.7,s  1.7) java.util.HashMap::putVal
	(t  0.8,s  0.6) psy.lob.saw.ProfilingBenchmarks::prepare
	(t  5.8,s  0.2) psy.lob.saw.generated.ProfilingBenchmarks_hashMapPutIsToBlame_jmhTest::hashMapPutIsToBlame_avgt_jmhStub
	(t  0.5,s  0.2) java.lang.ClassLoader::defineClass1
	(t  0.1,s  0.1) AGCT::GC Active[ERR=-2]
	(t  0.1,s  0.1) java.util.HashMap::hash
	(t  0.4,s  0.1) org.openjdk.jmh.runner.link.BinaryLinkClient::<init>
	(t  0.1,s  0.1) sun.misc.Unsafe::park

I also replaced the class method separator in the output to '::' which is the more standard notation (inside the JVM anyhow)

**Comment by nitsanw** [comment]
@ceeaspb GC is a sample error. For instance, I may have a JNI method called from Java method. The thread is at a safepoint while in JNI land, so JVM can go on and do a GC, but this does not mean the thread has stopped.

**Comment by ceeaspb** [comment]
@nitsanw ok I opened a ticket to get the error type meanings documented.

**Comment by ceeaspb** [comment]
new output looks great also

**Comment by nitsanw** [comment]
@ceeaspb  Have a play with the PR and test it out?

**Comment by ceeaspb** [comment]
@nitsanw I would certainly love to kick the tyres on this and other features soon. thanks
